name: Report a bug 🐛
about: Create a report to help us improve
labels: "bug"
assignees: tomkerkhove
issue_body: true
inputs:
- type: description
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    required: false
    placeholder: ex. email@example.com
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
    required: true
    placeholder: What did you expect to happen?
- type: textarea
  attributes:
    label: Actual Behavior
    description: Also tell us, what did you see is happen?
    required: true
    placeholder: Tell us what you see that is happening
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    required: false
    choices:
    - 0.1.0
    - experimental
