blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/tomkerkhove/k8s-event-grid-bridge/discussions/new
    about: Ask a question or request support for using Kubernetes Event Grid Bridge.
